version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.9  
    steps:
      - checkout                   
      - run:
          name: Install Dependencies
          command: pip install -r requirements.txt  
      - run:
          name: Run Python Script
          command: python EnergyProject.py  

